//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapshin_FitnessClub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSubscription
    {
        public int IdClient { get; set; }
        public int IdService { get; set; }
        public System.DateTime PurchaseTime { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
