//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapshin_FitnessClub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditHistory
    {
        public int Id { get; set; }
        public int IdEditor { get; set; }
        public System.DateTime TimeEdit { get; set; }
        public string EditSourceTableName { get; set; }
        public Nullable<int> IdEditSource { get; set; }
        public string NameEditSource { get; set; }
        public string EditSourceStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
