//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapshin_FitnessClub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditHistory
    {
        public int id { get; set; }
        public int idEditor { get; set; }
        public System.DateTime timeEdit { get; set; }
        public string editSourceTableName { get; set; }
        public Nullable<int> idEditSource { get; set; }
        public string nameEditSource { get; set; }
        public string editSourceStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
