//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapshin_FitnessClub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleService
    {
        public int IdSchedule { get; set; }
        public int IdService { get; set; }
        public Nullable<System.DateTime> BeginningDate { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
