//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapshin_FitnessClub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdService { get; set; }
        public decimal Cost { get; set; }
        public int Duration { get; set; }
        public int NumberOfLessons { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
